### PR TITLE
Add Approval revoke + OPERATOR to APPROVED + set_approval_for_all fixes

### LINKED ISSUE #159: Code duplicates.
I see a lot of duplicates in both `contracts` and `tests`. I think the codebase could be 1/3 of its current size. I suggest adding one more layer of abstraction. That would make code shorter and more readable.

### LINKED ISSUE #172: `set_approval_for_all` does not behave as expected
The current implementation of the `set_approval_for_all` method in the reference CEP-78 NFT standard implementation does not behave as expected. Ideally, this method should allow for the approval of multiple operators, enabling token owners to list their tokens on multiple marketplaces. However, this is not currently possible with the CEP-78 standard, limiting it to exclusive listings.

The method only approves tokens owned at the time of the entry point call, and does not cover tokens acquired later. This is because it simply loops over all of the owner's tokens and approves them individually, making the operation very expensive in terms of gas usage. In fact, a warning in the [comment next to the entry point](https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/568dd06707841906b13317d750d9b98cf9c41994/contract/src/main.rs#L801) advises developers to "DO NOT invoke this entrypoint unless absolutely necessary."

This unexpected behavior may also confuse dApp developers who are familiar with Ethereum's ERC-721 standard, potentially hurting the adoption of the Casper network.

To address these issues, we recommend changing the `set_approval_for_all` implementation in the following ways:

1. The entry point should allow owners to approve operators to manage all of their tokens in the contract, rather than individual tokens owned at the time of execution.
2. The entry point should make it possible to allow approval of multiple operators.
3. The entry point should have a corresponding getter method called `is_approved_for_all`, which returns whether an operator is approved to manage all tokens owned by an owner.

### LINKED ISSUE #174: Add ability to revoke approval permissions to CEP-78
Since we allow assignment of approval permissions, we need to provide the ability to revoke it as well.

### LINKED ISSUE #175: Support setting approval permissions to multiple operators
Current implementation allows this for a single operator but it should allow multiple assignments.

### LINKED ISSUE #176: Extend testing on set_approval_for_all
Set_approval_for_all updates permissions of the "assignee" to include 'approval' permission.  We need to test that once the permission is updated, it will also allow the "assignee" to assign 'approval' permissions to node operators.  Similarly, it should allow revocation of approval.

### PR DESCRIPTION
**Pull request by gRoussac**
This PR is for change of approve and approve_for_all entry point.

set_approve / revoke https://github.com/casper-ecosystem/cep-78-enhanced-nft/issues/155 == https://github.com/casper-ecosystem/cep-78-enhanced-nft/issues/174

set_approval / revoke_approve_all main fix #172 

https://github.com/casper-ecosystem/cep-78-enhanced-nft/issues/176 testing

code duplication #159 

multiple operators #175

### CODE REVIEW

**Comment by gRoussac** [comment]
@ACStoneCL I will come back to you later for your help to document those changes on approve and approve_all entry points

For now
- introducing a revoke entry point
- renaming operator dict to approved dict for approvals storage
- renaming operator argument to spender for the approve entry point
...
later 
- introducing an operators dict for operators storage
- adding a getter entry point :  is approved for all

**Comment by ACStone-MTS** [comment]
> @ACStoneCL I will come back to you later for your help to document those changes on approve and approve_all entry points
> 
> For now
> 
> * introducing a revoke entry point
> * renaming operator dict to approved dict for approvals storage
> * renaming operator argument to spender for the approve entry point
>   ...
>   later
> * introducing an operators dict for operators storage
> * adding a getter entry point :  is approved for all

@gRoussac Sure thing, I'll take a look and see what I can document as is. If anything is confusing, I'll reach out to make sure it's clear before I put it in writing.

**Comment by gRoussac** [comment]
@davidatwhiletrue @ihor Thanks again for your help for the specs, you can start reviewing now (and eventually run E2E tests with this wasm maybe if you have that in stock).

**Comment by gRoussac** [comment]
Once reviewed this PR will be squashed into branch feat-cesp.

File: contract/src/main.rs [hunk 1]
```diff
@@ -807,54 +813,61 @@ pub extern "C" fn approve() {
...
     }
 
-    let token_owner_key = match utils::get_dictionary_value_from_key::<Key>(
+    let owner = match utils::get_dictionary_value_from_key::<Key>(
         TOKEN_OWNERS,
         &token_identifier_dictionary_key,
     ) {
-        Some(token_owner) => token_owner,
+        Some(owner) => owner,
         None => runtime::revert(NFTCoreError::InvalidAccountHash),
```
Comment (davidatwhiletrue) [inline contract/src/main.rs]: Should this error be `InvalidTokenIdentifier`?

File: contract/src/main.rs [hunk 2]
```diff
@@ -807,54 +813,61 @@ pub extern "C" fn approve() {
...
 
-    let operator = utils::get_named_arg_with_user_errors::<Key>(
-        ARG_OPERATOR,
-        NFTCoreError::MissingApprovedAccountHash,
-        NFTCoreError::InvalidApprovedAccountHash,
-    )
-    .unwrap_or_revert();
+    let spender = match utils::get_optional_named_arg_with_user_errors::<Key>(
+        ARG_OPERATOR, // Deprecated in favor of ARG_SPENDER
+        NFTCoreError::MissingContractWhiteList,
```
Comment (davidatwhiletrue) [inline contract/src/main.rs]: why this error code? should it be `InvalidApprovedAccountHash` ?

File: README.md [hunk 3]
```diff
@@ -663,14 +671,14 @@ If it is set to `Hash`, you will need to reference the `HASH_BY_INDEX` dictionar
...
-The emitted events are encoded according to the [Casper Event Standard](https://github.com/make-software/casper-event-standard), and the schema can be known by an observer reading the `__events_schema` contract named key.
+The emitted events are encoded according to the [Casper Event Standard](https://github.com/make-software/casper-event-standard), and the schema is visible to an observer reading the `__events_schema` contract named key.
 
-For this CEP-78 reference implementation in particular, the events schema is the following:
+For this CEP-78 reference implementation, the events schema is as follows:
 
-| Event name      | Included values and type                                   |
-|-----------------|----------------------------------------------------------------------|
+| Event name      | Included values and type                                             |
+| --------------- | -------------------------------------------------------------------- |
```
Comment (ihor) [inline README.md]: `token_ids` should be removed from the `ApprovalForAll` event property list

File: contract/src/main.rs [hunk 4]
```diff
@@ -807,54 +813,61 @@ pub extern "C" fn approve() {
...
+        && match utils::get_dictionary_value_from_key::<Option<Key>>(
+            OPERATORS,
+            &utils::get_stringified_token_owner_item_key(owner),
+        ) {
+            Some(Some(maybe_operator)) => caller == maybe_operator,
+            Some(None) | None => false,
+        };
+
+    if !is_owner && !is_operator {
         runtime::revert(NFTCoreError::InvalidAccountHash);
```
Comment (davidatwhiletrue) [inline contract/src/main.rs:857]: should this error code be `InvalidTokenOwner` ?

File: README.md (hunk 3 above)
Comment (ihor) [reply README.md]: Separately, the `token_id` should be of type `String`. `Any` type isn't supported by the CES because of decoding issues.

File: contract/src/main.rs [hunk 5]
```diff
@@ -866,46 +879,127 @@ pub extern "C" fn approve() {
...
+            }
+        }
+    }
+
+    let owner = match utils::get_dictionary_value_from_key::<Key>(
+        TOKEN_OWNERS,
+        &token_identifier_dictionary_key,
+    ) {
+        Some(owner) => owner,
+        None => runtime::revert(NFTCoreError::InvalidAccountHash),
```
Comment (davidatwhiletrue) [inline contract/src/main.rs]: Should this error be `InvalidTokenIdentifier`?

File: README.md [hunk 6]
```diff
@@ -680,15 +688,15 @@ For this CEP-78 reference implementation in particular, the events schema is the
 | Migration       | -                                                                    |
 | VariablesSet    | -                                                                    |
 
-Token identifiers are stored under the `CLType` `Any` and the encoding depends on `NFTIdentifierMode`:.
+Token identifiers are stored under the `CLType` `Any` and the encoding depends on the `NFTIdentifierMode` modality:
 
-* `NFTIdentifierMode::Ordinal`: the `token id` is encoded as a byte `0x00` followed by a `u64` number.
-* `NFTIdentifierMode::Hash`: the `token_id` is encoded as a byte `0x01` followed by a `String`.
+- `NFTIdentifierMode::Ordinal`: the `token id` is encoded as a byte `0x00` followed by a `u64` number.
+- `NFTIdentifierMode::Hash`: the `token_id` is encoded as a byte `0x01` followed by a `String`.
```
Comment (ihor) [inline README.md]: Two paragraphs above should be removed because the `token_id` type was changed to `String`, which can be parsed by a generic parser

File: contract/src/main.rs [hunk 7]
```diff
@@ -1013,27 +1132,43 @@ pub extern "C" fn transfer() {
...
+            OPERATORS,
+            &source_owner_item_key,
+        ) {
+            Some(Some(maybe_operator)) => caller == maybe_operator,
+            Some(None) | None => false,
+        };
+
+    // Revert if caller is not owner nor approved nor an operator.
+    if !is_owner && !is_approved && !is_operator
+    // && !is_operator
```
Comment (davidatwhiletrue) [inline contract/src/main.rs]: remove this commented line?

File: contract/src/events/events_ces.rs [hunk 8]
```diff
@@ -43,58 +40,65 @@ impl Burn {
...
         }
     }
 }
 
 #[derive(Event, Debug, PartialEq, Eq)]
-pub struct Transfer {
+pub struct ApprovalForAll {
     owner: Key,
     operator: Option<Key>,
+}
```
Comment (ihor) [inline contract/src/events/events_ces.rs:76]: Since, the `ApprovalForAll` event doesn't have its `RevokeForAll` counterpart then a boolean flag should be added to indicate the action. I would call it `is_approved`.

Or should it be treated as always `true` and the `RevokeForAll` will be added later?

File: README.md [hunk 9]
```diff
@@ -663,14 +671,14 @@ If it is set to `Hash`, you will need to reference the `HASH_BY_INDEX` dictionar
...
 
-The emitted events are encoded according to the [Casper Event Standard](https://github.com/make-software/casper-event-standard), and the schema can be known by an observer reading the `__events_schema` contract named key.
+The emitted events are encoded according to the [Casper Event Standard](https://github.com/make-software/casper-event-standard), and the schema is visible to an observer reading the `__events_schema` contract named key.
 
-For this CEP-78 reference implementation in particular, the events schema is the following:
+For this CEP-78 reference implementation, the events schema is as follows:
 
-| Event name      | Included values and type                                   |
-|-----------------|----------------------------------------------------------------------|
+| Event name      | Included values and type                                             |
```
Comment (davidatwhiletrue) [inline README.md]: Please add here `ApprovalRevoked` event.

File: contract/src/main.rs [hunk 10]
```diff
@@ -914,54 +1008,47 @@ pub extern "C" fn set_approval_for_all() {
...
-            ));
+            casper_event_standard::emit(ApprovalForAll::new(caller, operator));
         }
         EventsMode::CEP47 => {
-            for callers_owned_token in callers_owned_tokens {
+            let caller_owned_tokens = match utils::get_reporting_mode() {
+                OwnerReverseLookupMode::NoLookUp => utils::get_owned_token_ids_by_token_number(),
+                OwnerReverseLookupMode::Complete => utils::get_owned_token_ids_by_page(),
+            };
+            for callers_owned_token in caller_owned_tokens {
```
Comment (ihor) [inline contract/src/main.rs]: I think here we should also have the `ApprovalForAll` event. The CEP-47 event mode refers to CEP-47 standard event implementation, and to the standard itself.

**Review by ihor — CHANGES_REQUESTED** [review]
@gRoussac please check my comments and questions.

Is that correct that at the moment there will be no possibility to revoke approval for all and that it will be added later?

**Review by davidatwhiletrue — CHANGES_REQUESTED** [review]
@gRoussac, please see my comments .

File: README.md (hunk 3 above)
Comment (gRoussac) [reply README.md]: @ihor 
> Is that correct that at the moment there will be no possibility to revoke approval for all and that it will be added later?

There is a possibility to revoke an operator but this was not correctly tested so I added a test below the approve_for_all test to test if revocation as operator occurred correctly.

https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/4cbda35b24509c2e0507c1f9a5271c3c641fa530

File: contract/src/main.rs (hunk 7 above)
Comment (gRoussac) [reply contract/src/main.rs]: done thanks

File: contract/src/main.rs (hunk 2 above)
Comment (gRoussac) [reply contract/src/main.rs]: Thanks please check that [commit](https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/c632e91fd84f7e4927cd01145d2027b894d25c2d), MissingApprovedAccountHash gets deprecated because ARG_OPERATOR becomes optional. Adding two new errors for explicit spender errors and fixing that copy-paste typo.

File: contract/src/main.rs (hunk 1 above)
Comment (gRoussac) [reply contract/src/main.rs]: Hi, so this error says owner not found for this particular token identifier. It is already [this error](https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/feat-cesp/contract/src/main.rs#L822) in the feat-cesp branch, so I am keeping it like that for both occurrences approve/revoke. To me this is correct behavior to say the owner is not found, thus his account hash is not found as a result. May you find this incorrect then let's raise another issue on dev cesp-branch for that.

File: contract/src/main.rs (hunk 5 above)
Comment (gRoussac) [reply contract/src/main.rs]: Thanks please see above comment on first occurrence

File: contract/src/main.rs (hunk 4 above)
Comment (gRoussac) [reply contract/src/main.rs:857]: Thanks I think this is current error code sent for this case and what I tested in corresponding tests.

https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/feat-cesp/contract/src/main.rs#L827

File: README.md (hunk 6 above)
Comment (gRoussac) [reply README.md]: Thanks please check that commit, let me know if I missed something

https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/ed86eab5d148af6c9cabbbcb48bd1dac01d21521

File: README.md (hunk 9 above)
Comment (gRoussac) [reply README.md]: Thanks please kindly check that commit https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/ed86eab5d148af6c9cabbbcb48bd1dac01d21521

File: README.md (hunk 3 above)
Comment (gRoussac) [reply README.md]: https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/092e49d9edb9bd2c645a248c4382e2971e587a8d

File: README.md (hunk 6 above)
Comment (gRoussac) [reply README.md]: https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/092e49d9edb9bd2c645a248c4382e2971e587a8d

File: README.md (hunk 9 above)
Comment (gRoussac) [reply README.md]: https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/092e49d9edb9bd2c645a248c4382e2971e587a8d

File: contract/src/main.rs (hunk 1 above)
Comment (davidatwhiletrue) [reply contract/src/main.rs]: Ok, makes sense to raise this in a separate issue. My concern was that the same error could be thrown in two different situations: (1) token identifier not found; (2) caller != owner.

Comment (gRoussac) [reply contract/src/main.rs]: Let's introduce a new error, please check https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/6fa19fef276a4b496c994f48f2031a421697d437 thanks

File: contract/src/main.rs (hunk 5 above)
Comment (gRoussac) [reply contract/src/main.rs]: https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/6fa19fef276a4b496c994f48f2031a421697d437

File: contract/src/events/events_ces.rs (hunk 8 above)
Comment (gRoussac) [reply contract/src/events/events_ces.rs:76]: Hi, Please check that commit https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/59ea32601f19c61e4a27a2aafcc0c48ef221034e, please let me know if I missed anything on this new event thanks

Comment (gRoussac) [reply contract/src/events/events_ces.rs:76]: https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/135a3fbb64bbccb37d88867410fe0cf455faffa7

Comment (gRoussac) [reply contract/src/events/events_ces.rs:76]: Right now I have `RevokedForAll` which is not alike `ApprovalRevoked` nomenclature. Shall I rename to `RevokedForAll` to `ApprovalForAllRevoked` ?

File: tests/src/burn.rs [hunk 11]
```diff
@@ -544,6 +517,7 @@ fn should_not_burn_in_non_burn_mode() {
     support::assert_expected_error(error, 106, "InvalidBurnMode(106) must have been raised");
 }
 
+// This test is not really relevant anymore as approve_for_all does not check burnt tokens anymore
```
Comment (ACStone-MTS) [inline tests/src/burn.rs]:
```suggestion
// This test is no longer relevant as approve_for_all does not check burnt tokens anymore
```

Code comment, so probably doesn't need proofreading and you can safely ignore this review comment - just saw it while I was looking through.

**Review by ACStone-MTS — APPROVED** [review]
Documentation portion LGTM

File: contract/src/events/events_ces.rs (hunk 8 above)
Comment (ihor) [reply contract/src/events/events_ces.rs:76]: Let's have `RevokedForAll`, it provides some symmetry with `ApprovalForAll`

File: contract/src/main.rs [hunk 12]
```diff
@@ -914,54 +1011,53 @@ pub extern "C" fn set_approval_for_all() {
...
-    for token_id in &callers_owned_tokens {
-        // We assume a burned token cannot be approved
-        if utils::is_token_burned(token_id) {
-            continue;
-        }
+    let owner_operator_item_key = utils::key_and_value_to_str(&caller, &operator);
+    utils::upsert_dictionary_value_from_key(
+        OPERATORS,
+        &owner_operator_item_key,
+        if approve_all { Some(operator) } else { None },
```
Comment (ihor) [inline contract/src/main.rs]: Do we need `Some(operator)` here since it's already defined by the dictionary key, we could use store the boolean `approve_all` value here.

**Review by ihor — CHANGES_REQUESTED** [review]
@gRoussac please check my comments

File: contract/src/main.rs (hunk 12 above)
Comment (gRoussac) [reply contract/src/main.rs]: Hi, this dictionary stores the key (owner/operator) and Option<Key> as value indeed. I guess it could store a boolean but then we can not query the dictionary from the value (not sure it this makes sense anyway) and I thought this would make more sense to be able to have the direct operator as value here. Let me try with a boolean though as I guess reverse lookup from dictionary value is anyway not possible.

Comment (gRoussac) [reply contract/src/main.rs]: Please check that commit 

https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/7314d36cb43369fbe178eaa3bca1a84c70ed04b8

I am a bit circumspect of the difference between APPROVED and OPERATORS. now, one deal with Option::<Key>, the second with booleans for values which is not super consistent but it works as well. It's probably lighter on storage to save a boolean than an account though.

File: contract/src/main.rs (hunk 1 above)
Comment (gRoussac) [reply contract/src/main.rs]: I think this time I changed all occurrences from error 28 to 147.

Please check that commit 
https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/7314d36cb43369fbe178eaa3bca1a84c70ed04b8

I had to change a test `should_return_expected_error_when_burning_non_existing_token` that was expecting error 28, now 147.

File: contract/src/main.rs (hunk 10 above)
Comment (gRoussac) [reply contract/src/main.rs]: Hi, I committed this change however I am checking with the rest of the team is this is really what was intended. 

https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/181/commits/2eee528a7e30d8b44e9451f9abd722ea9b75dfc3

**Review by davidatwhiletrue — APPROVED** [review]
LGTM. Thanks @gRoussac

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Review by ihor — APPROVED** [review]

**Review by ihor — CHANGES_REQUESTED** [review]
@gRoussac can we make CEP-47 style event names prefixed with `cep78_` like it was done in the contracts that worked CPE-78 and added CEP-47 style events themselves?

Like in this [example](https://cspr.live/deploy/926c008ba71ec9e45201dd3f7df8b51bfb0d23cce3652acf11c92c959c864cd3): 
Screenshot 2023-03-14 at 20 12 17

**Review by ihor — APPROVED** [review]
